# Generated by Django 2.1.2 on 2018-11-05 16:36

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import midas.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.UUIDField()),
                ("begin_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(null=True)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "properties",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.UUIDField()),
                ("identification_number", midas.models.UnboundedCharField()),
                ("model", midas.models.UnboundedCharField(default=str)),
                (
                    "status",
                    midas.models.UnboundedCharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("unavailable", "Unavailable"),
                            ("removed", "Removed"),
                        ]
                    ),
                ),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "properties",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
            options={"abstract": False},
        ),
    ]
