# Generated by Django 2.2.5 on 2019-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_squashed_0007_post_make_application_user_scope_blankable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE INDEX CONCURRENTLY authent_accesstoken_revoked_after_140f4bfb ON authent_accesstoken (revoked_after);"
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='accesstoken',
                    name='revoked_after',
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        )
    ]
