# Generated by Django 2.2.7 on 2019-11-26 09:42

from django.db import migrations


def fill_default_scopes(apps, schema_editor):
    Application = apps.get_model("authent", "Application")

    for application in Application.objects.all():
        application.users_allowed_scopes = application.scopes.copy()
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_pre_add_scope_restrictions_for_application_users'),
    ]

    operations = [
        migrations.RunPython(fill_default_scopes, migrations.RunPython.noop),
    ]
