# Generated by Django 2.1.3 on 2019-01-25 09:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import mds.models


class Migration(migrations.Migration):

    dependencies = [("mds", "0002_area_color")]

    operations = [
        migrations.AddField(
            model_name="eventrecord",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="eventrecord",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="dn_status",
            field=mds.models.UnboundedCharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("unavailable", "Unavailable"),
                    ("removed", "Removed"),
                    ("unknown", "Unknown"),
                ],
                default="unavailable",
            ),
        ),
        migrations.AlterField(
            model_name="eventrecord",
            name="saved_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="eventrecord", unique_together={("device", "timestamp")}
        ),
    ]
