# Generated by Django 2.1.4 on 2019-01-10 12:18

from django.db import migrations
from django.db.models import Q


def migrate_labels(apps, schema_editor):
    Area = apps.get_model("mds", "Area")
    Polygon = apps.get_model("mds", "Polygon")
    for area in Area.objects.filter(Q(label__isnull=True) | Q(label="")):
        area.label = "area_{}".format({area.pk})
        area.save()
    for polygon in Polygon.objects.filter(Q(label__isnull=True) | Q(label="")):
        polygon.label = "polygon_{}".format({area.pk})
        polygon.save()


class Migration(migrations.Migration):

    dependencies = [("mds", "0002_update_area_polygons")]

    operations = [migrations.RunPython(migrate_labels)]
