# Generated by Django 2.1.4 on 2019-01-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0002_update_area_polygons'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='telemetry',
            index_together={('device', 'timestamp')},
        ),
    ]
