# Generated by Django 2.1.4 on 2019-01-10 12:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import mds.models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [("mds", "0003_fill_area_polygon_labels")]

    operations = [
        migrations.AddField(
            model_name="area",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, encoder=rest_framework.utils.encoders.JSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="label",
            field=mds.models.UnboundedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name="polygon",
            name="label",
            field=mds.models.UnboundedCharField(unique=True),
        ),
    ]
