# Generated by Django 2.1.5 on 2019-01-25 13:43

from django.db import migrations
import mds.models


class Migration(migrations.Migration):

    dependencies = [("mds", "0005_auto_20190122_1300")]

    operations = [
        migrations.AddField(
            model_name="eventrecord",
            name="device_status",
            field=mds.models.UnboundedCharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("unavailable", "Unavailable"),
                    ("removed", "Removed"),
                    ("unknown", "Unknown"),
                ],
                default="",
            ),
            preserve_default=False,
        )
    ]
