# Generated by Django 2.1.5 on 2019-01-25 15:22

from django.db import migrations
import mds.models


class Migration(migrations.Migration):

    dependencies = [("mds", "0006_provider_device_category")]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="authentication_token",
            field=mds.models.UnboundedCharField(
                default="", verbose_name="Authentication token"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="base_api_url",
            field=mds.models.UnboundedCharField(
                default="", verbose_name="Base API URL"
            ),
            preserve_default=False,
        ),
    ]
