# Generated by Django 2.1.5 on 2019-01-29 16:41

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import mds.models


class Migration(migrations.Migration):

    dependencies = [("mds", "0008_provider_authentication")]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="api_configuration",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=mds.models.api_configuration_default,
                verbose_name="API Configuration",
            ),
        )
    ]
