# Generated by Django 2.1.7 on 2019-05-17 11:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0022_relabel_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='colors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='colors for distinguishing provider icons'),
        ),
    ]
