# Generated by Django 2.1.10 on 2019-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mds", "0034_post_default_device_saved_at")]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="skip",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
