# Generated by Django 2.1.5 on 2019-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0049_pre_migrate_to_policy_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='daily_penalty',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='fixed_price',
        ),
    ]
